# Generated by Django 3.1.7 on 2021-04-10 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0003_auto_20210410_0806'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='has_admin',
            field=models.BooleanField(default=False),
        ),
    ]
