# Generated by Django 3.1.7 on 2021-04-14 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dissertation',
            name='docfile',
            field=models.FileField(blank=True, upload_to='disserta'),
        ),
    ]
