# Generated by Django 3.1.7 on 2021-04-05 13:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('system', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Professor',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('system.user',),
        ),
        migrations.CreateModel(
            name='ProfessorFields',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_adminstrator', models.BooleanField(default=False)),
                ('grade', models.CharField(choices=[('0', 'Instructor'), ('1', 'Assistant'), ('2', 'Associate'), ('3', 'Professor')], max_length=10)),
                ('last_university', models.CharField(max_length=100)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='system.group')),
                ('professor', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='professor.professor')),
            ],
        ),
        migrations.CreateModel(
            name='PHDRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_id', models.CharField(blank=True, max_length=10)),
                ('status', models.IntegerField(choices=[(0, 'Rejected'), (1, 'Accepted'), (2, 'In Progress')], default=2)),
                ('clause_a', models.JSONField()),
                ('clause_b', models.CharField(max_length=20)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('manager_ok', models.BooleanField(default=False)),
                ('staff_ok', models.BooleanField(default=False)),
                ('professor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='professor.professor')),
            ],
        ),
        migrations.CreateModel(
            name='MasterRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_id', models.CharField(blank=True, max_length=10)),
                ('status', models.IntegerField(choices=[(0, 'Rejected'), (1, 'Accepted'), (2, 'In Progress')], default=2)),
                ('type_1', models.SmallIntegerField()),
                ('type_2', models.SmallIntegerField()),
                ('created_at', models.DateField(auto_now_add=True)),
                ('manager_ok', models.BooleanField(default=False)),
                ('staff_ok', models.BooleanField(default=False)),
                ('orientation', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='system.orientation')),
                ('professor', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='professor.professor')),
            ],
        ),
    ]
